### ISSUE TITLE
Grafana configuration requires explicit port number broken in OpenShift

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#277]
`GET /health` sees this in logs:

```
[ERROR] io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
Caused by: java.lang.IllegalArgumentException: port p must be in range 0 <= p <= 65535
	at io.vertx.core.impl.Arguments.requireInRange(Arguments.java:44)
	at io.vertx.core.net.impl.SocketAddressImpl.<init>(SocketAddressImpl.java:32)
	at io.vertx.core.net.SocketAddress.inetSocketAddress(SocketAddress.java:37)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1106)
	at io.vertx.core.http.impl.HttpClientImpl.createRequest(HttpClientImpl.java:1074)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:591)
	at io.vertx.ext.web.client.impl.HttpContext.handlePrepareRequest(HttpContext.java:344)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:288)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:275)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:272)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:282)
	at io.vertx.ext.web.client.impl.HttpContext.prepareRequest(HttpContext.java:168)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:331)
	at io.vertx.ext.web.client.impl.HttpRequestImpl.send(HttpRequestImpl.java:301)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.checkUri(HealthGetHandler.java:129)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.handle(HealthGetHandler.java:102)
	at com.redhat.rhjmc.containerjfr.net.web.handlers.HealthGetHandler.handle(HealthGetHandler.java:63)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

`oc describe` snippet:

```
    Environment:
      CONTAINER_JFR_PLATFORM:             com.redhat.rhjmc.containerjfr.platform.openshift.OpenShiftPlatformStrategy
      CONTAINER_JFR_SSL_PROXIED:          true
      CONTAINER_JFR_ALLOW_UNTRUSTED_SSL:  true
      CONTAINER_JFR_WEB_PORT:             8181
      CONTAINER_JFR_EXT_WEB_PORT:         443
      CONTAINER_JFR_WEB_HOST:             containerjfr-default.apps-crc.testing
      CONTAINER_JFR_LISTEN_PORT:          9090
      CONTAINER_JFR_EXT_LISTEN_PORT:      443
      CONTAINER_JFR_LISTEN_HOST:          containerjfr-command-default.apps-crc.testing
      GRAFANA_DASHBOARD_URL:              https://containerjfr-grafana-default.apps-crc.testing
      GRAFANA_DATASOURCE_URL:             http://172.25.131.63:8080
      CONTAINER_JFR_DISABLE_JMX_AUTH:     true
      CONTAINER_JFR_DISABLE_SSL:          true
```

The problematic execution pointed to by the stack trace appears to be (`HealthGetHandler.java`):

```
        checkUri(GRAFANA_DASHBOARD_ENV, "/api/health", dashboardAvailable);

    private void checkUri(String envName, String path, CompletableFuture<Boolean> future) {
        if (this.env.hasEnv(envName)) {
            URI uri;
            try {
                uri = new URI(this.env.getEnv(envName));
            } catch (URISyntaxException e) {
                logger.warn(e);
                future.complete(false);
                return;
            }
            webClient
                    .get(uri.getPort(), uri.getHost(), path)
                    .ssl("https".equals(uri.getScheme()))
                    .timeout(5000)
                    .send(
                            handler -> {
                                if (handler.failed()) {
                                    future.complete(false);
                                    this.logger.info(new IOException(handler.cause()));
                                    return;
                                }
                                future.complete(handler.result().statusCode() == 200);
                            });
        } else {
            future.complete(false);
        }
    }

```

I think, from a reading, that the problem is that the `uri` is `https://containerjfr-grafana-default.apps-crc.testing`, which has no explicit port number, so `uri.getPort()` is `-1` and the request send fails.

**Comment by andrewazores** [comment]
The fix should be to use `.get(String, String)` if `uri.getPort() < 0 || uri.getPort() > 65535`. This allows the Vert.x WebClient to decide what port number to use, which may be the default for the URI scheme (http/80 or https/443), or some other default port number configured on the webClient instance.
